python predict_attention.py \
    --onto ./samples/ontology.txt \
    --snp2gene ./samples/snp2gene.txt \
    --bfile ./samples/train \
    --cov ./samples/train.cov \
    --pheno ./samples/train.pheno \
    --jobs 8 \
    --batch-size 128 \
    --model ./samples/output_model.pt.20 \
    --cuda 0 \
    --out ./samples/output_model \
    --system_annot ./GO_files/goID_2_name.tab
